theme: jekyll-theme-minimal
title: 💻✒️📄🌟
description: Nikolaos Margaris' CV
show_downloads: "true"
docs:
  pdf_url: "docs/Nikolaos_Margaris_Resume.pdf"
  doc_url: "docs/Nikolaos_Margaris_Resume.docx"
  odt_url: "docs/Nikolaos_Margaris_Resume.odt"
