theme: jekyll-theme-minimal
title: 💻✒️📄🌟
description: Nikolaos Margaris' CV
show_downloads: "true"
docs:
  pdf_url: "docs/CV - Nikolaos Margaris - 2025.pdf"
  doc_url: "docs/CV - Nikolaos Margaris - 2025.docx"
  odt_url: "docs/CV - Nikolaos Margaris - 2025.odt"
